version: '2'
services:
    nucleus-app:
        image: nucleus
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://nucleus-postgresql:5432/nucleus
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nucleus-postgresql:
        extends:
            file: postgresql.yml
            service: nucleus-postgresql
